TFE_GestionDeStockEtVenteEnLigne/Models/Metier/Produit.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TFE_GestionDeStockEtVenteEnLigne.Models.Metier;

namespace TFE_GestionDeStockEtVenteEnLigne.Models
{
    [Bind("ID,CategorieID,MotClef,Ref,Denomination,Prix,QuantiteEmballage,NBPieceEmballage,TVA,CompteCompta,Description,Marque,QuantiteStock,Image")]
    public class Produit
    {
        public int ID { get; set; }

        public int CategorieID { get; set; }
        public int TauxTVAID { get; set; }

        [Display(Name = "Référence")]
        public String Ref { get; set; }
        [Display(Name = "Dénomination")]
        public String Denomination { get; set; }

        [Range(0, double.MaxValue)]
        [Display(Name = "Prix TTC")]
        public double Prix { get; set; }

        [Range(0, int.MaxValue)]
        [Display(Name = "Quantité d'emballages en stock")]
        public int QuantiteEmballage { get; set; }

        [Range(0, int.MaxValue)]
        [Display(Name = "Quantité par emballage")]
        public int NBPieceEmballage { get; set; }

        [Range(0, int.MaxValue)]
        public int TVA { get; set; }
        [Display(Name = "Taux TVA")]
        public TauxTVA TauxTVA  { get; set; }
        [Display(Name = "Compte comptable")]
        public String CompteCompta{ get; set; }

        public String Description { get; set; }

        public String Marque { get; set; }

        [Range(0, int.MaxValue)]
        [Display(Name = "Quantité en vrac")]
        public int QuantiteStock { get; set; }

        [Range(0, int.MaxValue)]
        [Display(Name = "Quantité totale")]
        public int QuantiteStockTotal { get; set; }

        public Byte[] Image { get; set; }

        public bool Visible { get; set; }
        [Display(Name = "Date de création")]
        public DateTime Date { get; set; }

        public ICollection<Possede> Possede { get; set; }
        [Display(Name = "Mots clés")]
        public ICollection <ProduitMotClef>MotClef { get; set; }
        public ICollection<Panier> Panier { get; set; }
        [Display(Name = "Catégorie")]
        public Categorie Categorie { get; set; }
        public ICollection<Valeur> Valeur { get; set; }
        public ICollection<Provient> Provients { get; set; }

        public static bool PredicatDelNotVisible(Produit p)
        {
            return !p.Visible;
        }
    }
}

TFE_GestionDeStockEtVenteEnLigne/Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TFE_GestionDeStockEtVenteEnLigne.Data;
using TFE_GestionDeStockEtVenteEnLigne.Models.Metier;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using TFE_GestionDeStockEtVenteEnLigne.Models;

namespace TFE_GestionDeStockEtVenteEnLigne.Controllers
{
    [Authorize(Roles = "gestionnaire,client")]
    public class PaniersController : Controller
    {
        private readonly TFEContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PaniersController(UserManager<ApplicationUser> userManager,TFEContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Paniers
        public async Task<IActionResult> Index()
        {
            var IdUser = _userManager.GetUserId(User);
            var tFEContext = _context.Panier.Include(p => p.Produit).Where(p=>p.RegisterViewModelID == IdUser);
            ViewData["prodNotDispo"] = TempData["prodNotDispo"];
            return View(await tFEContext.ToListAsync());
        }

        // GET: Paniers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier
                .Include(p => p.Produit)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }

        // GET: Paniers/Create
        public IActionResult Create()
        {
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID");
            return View();
        }

        // POST: Paniers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,RegisterViewModelID,ProduitID")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(panier);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID", panier.ProduitID);
            return View(panier);
        }

        // GET: Paniers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier.SingleOrDefaultAsync(m => m.ID == id);
            if (panier == null)
            {
                return NotFound();
            }
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID", panier.ProduitID);
            return View(panier);
        }

        // POST: Paniers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,RegisterViewModelID,ProduitID")] Panier panier)
        {
            if (id != panier.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(panier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PanierExists(panier.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID", panier.ProduitID);
            return View(panier);
        }

        // GET: Paniers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier
                .Include(p => p.Produit)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }
        public async Task<IActionResult> DeletePanier()
        {
            var IdUser = _userManager.GetUserId(User);
            var panier =  _context.Panier.ToArray();
            _context.Panier.RemoveRange(panier);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var panier = await _context.Panier.SingleOrDefaultAsync(m => m.ID == id);
            _context.Panier.Remove(panier);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PanierExists(int id)
        {
            return _context.Panier.Any(e => e.ID == id);
        }
    }
}

TFE_GestionDeStockEtVenteEnLigne/ViewComponents/RechercheViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TFE_GestionDeStockEtVenteEnLigne.Data;
using TFE_GestionDeStockEtVenteEnLigne.Models;
using Microsoft.EntityFrameworkCore;

namespace TFE_GestionDeStockEtVenteEnLigne.ViewComponents
{
    public class RechercheViewComponent: ViewComponent
    {
        private readonly TFEContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RechercheViewComponent(UserManager<ApplicationUser> userManager, TFEContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categorie = await _context.Categories.Include(c => c.CategorieEnfant).ToListAsync();
            int i = 0;
            while ( i< categorie.Count)
            {
                if (categorie[i].CategorieParent != null)
                {
                    categorie.Remove(categorie[i]);
                }
                else
                {
                    ++i;
                }
            }
            return View(categorie);
        }
    }
}

TFE_GestionDeStockEtVenteEnLigne/Views/Produits/Delete.cshtml
@model TFE_GestionDeStockEtVenteEnLigne.Models.Produit

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.Ref)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ref)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Denomination)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Denomination)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuantiteEmballage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuantiteEmballage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NBPieceEmballage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NBPieceEmballage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TVA)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TVA)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CompteCompta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompteCompta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Marque)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Marque)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuantiteStock)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuantiteStock)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

TFE_GestionDeStockEtVenteEnLigne/Views/Produits/Details.cshtml
@model TFE_GestionDeStockEtVenteEnLigne.Models.Produit

@{
    ViewData["Title"] = "Details";
}

<h2>Détails</h2>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ref)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ref)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Denomination)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Denomination)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Marque)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Marque)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categorie.Nom)
        </dd>*@
        @{
            var NonValeur = Model.Valeur.ToArray();
            @for (int i = 0; i < Model.Valeur.Count; i++)
            {
                <dt>
                    @NonValeur[i].Attribut.Nom
                </dt>
                <dd>
                    @NonValeur[i].Valeurs
                </dd>
            }
        }
        @*<dt>
            @Html.DisplayNameFor(model => model.Valeur)
        </dt>

        <dd>
            @foreach (var item in Model.Valeur)
            {

                @Html.DisplayFor(model => item.Valeurs)
                @Html.DisplayFor(model => item.Attribut.Mesure)
                if (!(Model.Valeur.Last().Equals(item)))
                {
                    @:,
                }
            }
        </dd>*@
        @*<dt>
            @Html.DisplayNameFor(model => model.MotClef)
        </dt>

        <dd>
            @{
                var a = Model.MotClef.ToArray();
                @for (int i = 0; i < Model.MotClef.Count; i++)
                {
                    @a[i].MotClef.Valeur;
                    if (i < Model.MotClef.Count - 1)
                    {
                        @:,
                    }
                }
            }*@
        @*@foreach (var item in Model.MotClef)
        {
            @Html.DisplayFor(model => item.MotClef.Valeur)@:,
        }*@
        @*</dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TauxTVA)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TauxTVA.Valeur)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.QuantiteEmballage)*@Qté Emball en stock
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuantiteEmballage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NBPieceEmballage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NBPieceEmballage)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.CompteCompta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompteCompta)
        </dd>*@
        @*<dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.QuantiteStock)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuantiteStock)
        </dd>*@
        @*<dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>*@
        @*<dd>
            @Html.DisplayFor(model => model.Image)
        </dd>*@
    </dl>
    @{
        var base64 = Convert.ToBase64String(Model.Image);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }

    <img class="imagePetite" src="@imgSrc" id="myBtn" />
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <img src="@imgSrc" class="imageGrande" />
        </div>
    </div>

</div>

<div>
    <form asp-controller="Account" asp-action="AddPanier" asp-route-id="@Model.ID" method="post">
        <input class="col-lg-12 " type="number" name="Quantite" min="1" placeholder="Qté emballages voulue" required />
        <input class="col-lg-12 btn btn-default textRed" type="submit" value="Ajouter au panier" />
    </form>
    @*<a asp-action="Edit" asp-route-id="@Model.ID">Editer</a> |*@
    @if (ViewData["source"] != null && ViewData["source"].ToString() == "panier")
    {

        <a asp-controller="Paniers" asp-action="Index">Retour</a>
    }
    else
    {
        <a asp-action="Index">Retour</a>
    }


</div>

<script>
    // Get the modal
    var modal = document.getElementById('myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal
    btn.onclick = function () {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

TFE_GestionDeStockEtVenteEnLigne/Views/Produits/Index.cshtml
@model IEnumerable<TFE_GestionDeStockEtVenteEnLigne.Models.Produit>
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Index";
}


<div class="flexbox ">
    @*myCenter*@


    <div class="myCenterSearch ">
        <div class="hidden-xs">
            <div class="myborder ">
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="">
                        <ul class="connexion">
                            <li>
                                <a class="colorBlue btnConf btn  btn-lg btngrad" asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">Mon Profil</a>@*@ Hello UserManager.GetUserName(User)*@
                            </li>
                            <li>
                                <button type="submit" class="btn  btn-lg btnConf btngrad">Déconnexion</button> @*navbar-link btn-link*@
                            </li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="connexion">
                        <li>
                            <a class="colorBlue btnConf btn  btn-lg btngrad" asp-area="" asp-controller="Account" asp-action="Register">S'inscrire</a>
                        </li>
                        <li>
                            <a class="colorBlue btnConf btn  btn-lg btngrad" asp-area="" asp-controller="Account" asp-action="Login">Connexion</a>
                        </li>
                    </ul>

                }

            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="myborder">
                    @await Html.PartialAsync("_PanierView")
                </div>
            }
        </div>
        <div class="myborder">
            @await Component.InvokeAsync("Recherche")
        </div>
    </div>

    <div class="col-lg-12">
        <h2>Nos produits</h2>
        <div class="row">
            @ViewData["passtock"]
        </div>


        @if (@ViewData["cat"] != null)
        {
            <div>Catérgorie : @ViewData["cat"]</div>
        }
        @if (@ViewData["recherche"] != null)
        {
            <div>Recherche : @ViewData["recherche"]</div>
        }

        @if (User.Identity.IsAuthenticated)
        {
            if (User.IsInRole("gestionnaire"))
            {
                <p>
                    <a asp-action="Create">Nouveau</a> |
                    <a asp-action="Index" asp-route-qte="0">produits en rupture de stock</a>
                </p>
            }
        }
        @*<form asp-action="Index" method="get">
                <div class="form-action no-color">
                    <p>
                        Find: <input type="text" name="SearchStr" value="@ViewData["Filter"]" />
                        <input type="submit" value="Search" class="btn btn-default" />
                    </p>
                </div>
            </form>*@
        @*<table class="table ">
                <thead>
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.RefSort">
                                @Html.DisplayNameFor(model => model.Ref)
                            </a>
                        </th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.DenoSort">
                                @Html.DisplayNameFor(model => model.Denomination)
                            </a>
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Prix)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.QuantiteEmballage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NBPieceEmballage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TVA)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CompteCompta)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Marque)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.QuantiteStock)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Image)
                        </th>
                        <th>
                            <span>Image</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                     {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ref)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Denomination)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Prix)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.QuantiteEmballage)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NBPieceEmballage)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TVA)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CompteCompta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Marque)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.QuantiteStock)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Image)
                            </td>

                            <td>
                                @{
                                    var base64 = Convert.ToBase64String(item.Image);
                                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                                }
                                <img class="imagePetite" src="@imgSrc" id="myBtn" />
                                <div id="myModal" class="modal">
                                    <div class="modal-content">
                                        <span class="close">&times;</span>
                                        <img src="@imgSrc" class="imageGrande" />
                                    </div>
                                </div>
                            </td>
                             <td>
                            <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                            @if (User.Identity.IsAuthenticated)
                             {
                                if (User.IsInRole("gestionnaire"))
                                {
                                    <span> |</span> <a asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                                }
                                <form asp-controller="Account" asp-action="AddPanier" asp-route-id="@item.ID" method="post">
                                    <input type="number" name="Quantite" min="1" />
                                    <input type="submit" value="Ajouter au panier" class="btn btn-default" />
                                </form>
                             }
                            </td>
                        </tr>
                     }
                </tbody>
            </table>*@
        @if (Model.ToList().Count == 0)
        {
            <h1>Aucun produit pour le moment</h1>
        }
        @foreach (var item in Model)
        {
            <div class="panel panel-default col-lg-3 col-md-6 col-sm-12">
                <div class="panel-heading textover" data-toggle="tooltip" title="@item.Denomination">@Html.DisplayFor(modelItem => item.Denomination)</div>
                <div class="panel-body">
                    <div class="row">Prix: @Html.DisplayFor(modelItem => item.Prix)€</div>
                    <div class="row">Référence: @Html.DisplayFor(modelItem => item.Ref)</div>
                    @{
                        var base64 = Convert.ToBase64String(item.Image);
                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    }
                    <img class="imagePetite row " src="@imgSrc" id="myBtn" />
                    <div id="myModal" class="modal">
                        <div class="modal-content">
                            <span class="close">&times;</span>
                            <img src="@imgSrc" class="imageGrande" />
                        </div>
                    </div>
                    <div class="row">
                        <a asp-action="Details" asp-route-id="@item.ID">Détails</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("gestionnaire"))
                            {
                                <span> |</span> <a asp-action="Edit" asp-route-id="@item.ID">Editer</a>
                            }
                            <form asp-controller="Account" asp-action="AddPanier" asp-route-id="@item.ID" method="post">
                                <input class="col-lg-12 " type="number" name="Quantite" min="1" placeholder="Qté emballages voulue" required />
                                <input class="col-lg-12 btn btn-default colorBlue" type="submit" value="Ajouter au panier" />
                            </form>
                        }
                    </div>
                </div>
            </div>
        }


    </div>
</div>

<script>
    //image
    // Get the modal
    var modal = document.getElementById('myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal
    btn.onclick = function () {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>