TFE_GestionDeStockEtVenteEnLigne/Models/Metier/Commande.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TFE_GestionDeStockEtVenteEnLigne.Models
{
    public class Commande
    {
        public int ID { get; set; }
        public int? ClientID { get; set; }
        public String RegisterViewModelID { get; set; }
        public int? AdresseID { get; set; }
        [Display(Name = "Date de commande")]
        public DateTime DateCommade{ get; set; }
        [Display(Name = "Commande en cours")]
        public bool EnCours { get; set; }
        [Display(Name = "Commande envoyée")]
        public DateTime Envoie { get; set; }

        public virtual Facture Facture { get; set; }
        [Display(Name = "Adresse de facturation")]
        public Adresse AdresseFacturation { get; set; }
        public Client Client{ get; set; }
        public ICollection<Possede> Possede { get; set; }

        public Commande()
        {
            Possede = new List<Possede>();
        }
    }
}

TFE_GestionDeStockEtVenteEnLigne/Controllers/FacturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TFE_GestionDeStockEtVenteEnLigne.Data;
using TFE_GestionDeStockEtVenteEnLigne.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.NodeServices;
using System.Net.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;

namespace TFE_GestionDeStockEtVenteEnLigne.Controllers
{
    
    public class FacturesController : Controller
    {
        private readonly TFEContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FacturesController(UserManager<ApplicationUser> userManager, TFEContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Factures
        public async Task<IActionResult> Index()
        {
            var tFEContext = _context.Factures.Include(f => f.Commande);
            return View(await tFEContext.ToListAsync());
        }

        // GET: Factures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures
                .Include(f => f.Commande)
                    .ThenInclude(c=>c.Possede)
                        .ThenInclude(p=>p.Produit)
                        .Include(c=>c.Commande)
                            .ThenInclude(add=>add.AdresseFacturation)
                .SingleOrDefaultAsync(m => m.ID == id);
            ViewData["client"] = await _userManager.Users.SingleOrDefaultAsync(u => u.Id == facture.Commande.RegisterViewModelID);
            if (facture == null)
            {
                return NotFound();
            }

            return View(facture);
        }

        // GET: Factures/Create
        //public IActionResult Create()
        //{
        //    ViewData["ID"] = new SelectList(_context.Set<Commande>(), "ID", "ID");
        //    return View();
        //}

        // POST: Factures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("ID,Numero,DatePaiement")] Facture facture)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(facture);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    ViewData["ID"] = new SelectList(_context.Set<Commande>(), "ID", "ID", facture.ID);
        //    return View(facture);
        //}

        // GET: Factures/Edit/5
        [Authorize(Roles = "gestionnaire")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures.SingleOrDefaultAsync(m => m.ID == id);
            if (facture == null)
            {
                return NotFound();
            }
            ViewData["ID"] = new SelectList(_context.Set<Commande>(), "ID", "ID", facture.ID);
            return View(facture);
        }

        // POST: Factures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "gestionnaire")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Numero,DatePaiement")] Facture facture)
        {
            if (id != facture.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(facture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FactureExists(facture.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ID"] = new SelectList(_context.Set<Commande>(), "ID", "ID", facture.ID);
            return View(facture);
        }

        // GET: Factures/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var facture = await _context.Factures
        //        .Include(f => f.Commande)
        //        .SingleOrDefaultAsync(m => m.ID == id);
        //    if (facture == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(facture);
        //}

        // POST: Factures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var facture = await _context.Factures.SingleOrDefaultAsync(m => m.ID == id);
        //    _context.Factures.Remove(facture);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        private bool FactureExists(int id)
        {
            return _context.Factures.Any(e => e.ID == id);
        }
        [HttpGet]
        public async Task<IActionResult> Facture([FromServices] INodeServices nodeServices)
        {
            HttpClient hc = new HttpClient();
            //var host = Request.Host.ToString()+ Request.Path.ToString()+ Request.QueryString.ToString();
            //var b = Request.QueryString;
            string scheme = Request.Headers["Referer"].ToString();
            var htmlContent = await hc.GetStringAsync(scheme);
            string[] stringSeparators = new string[] { "</div><div class=\"veutpas\"></div>", "<div class=\"factureContenu\">" };
            String[] result1 = htmlContent.Split(stringSeparators, StringSplitOptions.None);

            var result = await nodeServices.InvokeAsync<byte[]>("./pdf", result1[1]);

            HttpContext.Response.ContentType = "application/pdf";

            HttpContext.Response.Headers.Add("x-filename", "report.pdf");
            HttpContext.Response.Headers.Add("Access-Control-Expose-Headers", "x-filename");
            HttpContext.Response.Body.Write(result, 0, result.Length);
            return new ContentResult();
        }
    }
}

TFE_GestionDeStockEtVenteEnLigne/Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TFE_GestionDeStockEtVenteEnLigne.Data;
using TFE_GestionDeStockEtVenteEnLigne.Models.Metier;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using TFE_GestionDeStockEtVenteEnLigne.Models;

namespace TFE_GestionDeStockEtVenteEnLigne.Controllers
{
    [Authorize(Roles = "gestionnaire,client")]
    public class PaniersController : Controller
    {
        private readonly TFEContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PaniersController(UserManager<ApplicationUser> userManager,TFEContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Paniers
        public async Task<IActionResult> Index()
        {
            var IdUser = _userManager.GetUserId(User);
            var tFEContext = _context.Panier.Include(p => p.Produit).Where(p=>p.RegisterViewModelID == IdUser);
            ViewData["prodNotDispo"] = TempData["prodNotDispo"];
            return View(await tFEContext.ToListAsync());
        }

        // GET: Paniers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier
                .Include(p => p.Produit)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }

        // GET: Paniers/Create
        public IActionResult Create()
        {
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID");
            return View();
        }

        // POST: Paniers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,RegisterViewModelID,ProduitID")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(panier);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID", panier.ProduitID);
            return View(panier);
        }

        // GET: Paniers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier.SingleOrDefaultAsync(m => m.ID == id);
            if (panier == null)
            {
                return NotFound();
            }
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID", panier.ProduitID);
            return View(panier);
        }

        // POST: Paniers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,RegisterViewModelID,ProduitID")] Panier panier)
        {
            if (id != panier.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(panier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PanierExists(panier.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ProduitID"] = new SelectList(_context.Produits, "ID", "ID", panier.ProduitID);
            return View(panier);
        }

        // GET: Paniers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier
                .Include(p => p.Produit)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }
        public async Task<IActionResult> DeletePanier()
        {
            var IdUser = _userManager.GetUserId(User);
            var panier =  _context.Panier.ToArray();
            _context.Panier.RemoveRange(panier);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var panier = await _context.Panier.SingleOrDefaultAsync(m => m.ID == id);
            _context.Panier.Remove(panier);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PanierExists(int id)
        {
            return _context.Panier.Any(e => e.ID == id);
        }
    }
}

TFE_GestionDeStockEtVenteEnLigne/Views/Commandes/Create.cshtml
@model TFE_GestionDeStockEtVenteEnLigne.Models.Adaptateur.CommandeAdresseAdaptateur

@{
    ViewData["Title"] = "Create";
}

<h2>Adresse de facturation</h2>
<form asp-action="Create">

    <div class="form-horizontal">
        <hr />

        @*<div class="form-group">
            <label class="col-md-3 control-label">Enlèvement en magasin?</label>
            <div class="col-md-9">*@
                @*@Html.CheckBox("enlevementMagasin", false)*@
                @*<div><input id="enlevementMagasin" type="checkbox" name="enlevementMagasin" class="moncheckbox" value="true" onchange="afficherAdd()"> <div id="Livraison">Oui</div></div>
            </div>
        </div>*@

        <div id="add" class="monPanier">
            <div class="form-group">
                <label class="col-md-2 control-label">Vos adresses :</label>
                <div class="col-md-10">
                    <select id="selectadr" onchange="selectAdresse()" asp-for="Adresse" class="selectpicker">
                        @foreach (var adr in Model.ListeAdresse)
                        {
                            <option>@adr.Localite,@adr.Rue,@adr.Numero,@adr.NumeroBoite,@adr.Pays,@adr.CodePostal,@adr.Comune</option>
                        }
                    </select>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Adresse.Localite" class="col-md-2 control-label">Localité*</label>
                <div class="col-md-10">
                    <input id="localite" asp-for="Adresse.Localite" class="form-control" value="@Model.ListeAdresse[0].Localite" required />
                    <span asp-validation-for="Adresse.Localite" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Adresse.Rue" class="col-md-2 control-label">Rue*</label>
                <div class="col-md-10">
                    <input id="rue" asp-for="Adresse.Rue" class="form-control" value="@Model.ListeAdresse[0].Rue" required />
                    <span asp-validation-for="Adresse.Rue" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Adresse.Numero" class="col-md-2 control-label">Numéro*</label>
                <div class="col-md-10">
                    <input id="numero" asp-for="Adresse.Numero" class="form-control" value="@Model.ListeAdresse[0].Numero" required />
                    <span asp-validation-for="Adresse.Numero" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Adresse.NumeroBoite" class="col-md-2 control-label">Numro de boite</label>
                <div class="col-md-10">
                    <input id="numboite" asp-for="Adresse.NumeroBoite" class="form-control" value="@Model.ListeAdresse[0].NumeroBoite" />
                    <span asp-validation-for="Adresse.NumeroBoite" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Adresse.Pays" class="col-md-2 control-label">Pays*</label>
                <div class="col-md-10">
                    <input id="pays" asp-for="Adresse.Pays" class="form-control" value="@Model.ListeAdresse[0].Pays" required />
                    <span asp-validation-for="Adresse.Pays" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Adresse.CodePostal" class="col-md-2 control-label">Code Postal*</label>
                <div class="col-md-10">
                    <input id="codepostal" asp-for="Adresse.CodePostal" class="form-control" value="@Model.ListeAdresse[0].CodePostal" required />
                    <span asp-validation-for="Adresse.CodePostal" class="text-danger"></span>
                </div>
            </div>
            @*<div class="form-group">
                <label asp-for="Adresse.Comune" class="col-md-2 control-label">Commune*</label>
                <div class="col-md-10">
                    <input id="comune" asp-for="Adresse.Comune" class="form-control" value="@Model.ListeAdresse[0].Comune" required />
                    <span asp-validation-for="Adresse.Comune" class="text-danger"></span>
                </div>
            </div>*@
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Valider" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Paniers" asp-action="Index">Annuler</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TFE_GestionDeStockEtVenteEnLigne/Views/Commandes/Delete.cshtml
@model TFE_GestionDeStockEtVenteEnLigne.Models.Commande

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Commande</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.DateCommade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCommade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnCours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnCours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Envoie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Envoie)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

TFE_GestionDeStockEtVenteEnLigne/Views/Commandes/Details.cshtml
@model TFE_GestionDeStockEtVenteEnLigne.Models.Commande

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Commande</h4>
    <hr />
    
    <dl class="dl-horizontal">
        @*<dd>
                @Html.DisplayFor(model => model.ID)
            </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.DateCommade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCommade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnCours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnCours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Envoie)
        </dt>
        <dd>
            @if (Model.Envoie > Model.DateCommade)
            {
                @Html.DisplayFor(model => model.Envoie)
            }
            else
            {
                <div>pas encore envoyé!</div>
            }
            @*@Html.DisplayFor(model => model.Envoie)*@
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AdresseFacturation)
        </dt>
        <dd>
            @Model.AdresseFacturation.ToString()
        </dd>

        @*@foreach (var item in Model.Possede)
        {
            <dt>
                produit
            </dt>
            <dd>
                @Html.DisplayFor(model => item.Produit.Denomination)
                <a asp-controller="Produits" asp-action="Details" asp-route-id="@item.Produit.ID">Details</a>
            </dd>
        }*@
    </dl>
    <table class="table">
        <thead>
            <tr>
                @*<th>
                        @Html.DisplayNameFor(model => model.RegisterViewModelID)
                    </th>*@
                <th>
                    Produits
                </th>
                <th>
                    Quantité
                </th>
                <th>
                    Image
                </th>
                <th>
                    Prix unitaire
                </th>
                <th>
                    Prix
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 0;
            }
            @foreach (var item in Model.Possede)
            {

                Possede p = new Possede();
                p.ProduitID = item.ProduitID;
                p.CommandeID = item.CommandeID;
                p.Quantite = item.Quantite;

                <tr id="@item.ProduitID">
                    <td>
                        <input id="@i" type="hidden" name="possedeId" asp-for="Possede.ToArray()[i].ID" />
                        <input id="@i" type="hidden" name="produitId" asp-for="Possede.ToArray()[i].ProduitID" />
                        <input id="@i" type="hidden" name="CommandeId" asp-for="Possede.ToArray()[i].CommandeID" />

                        @Html.DisplayFor(modelItem => item.Produit.ID)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantite)
                        @*<input id="@i" type="text" name="quantite" asp-for="Commande.Possede.ToArray()[i].Quantite" />*@
                    </td>
                    <td>
                        @{
                            @if (item.Produit.Image != null)
                            {
                                var base64 = Convert.ToBase64String(item.Produit.Image);
                                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                                <img class="imagePetite" src="@imgSrc" id="myBtn" />
                            }
                        }
                        @*@Html.DisplayFor(modelItem => item.Produit.Image)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produit.Prix)
                    </td>
                    <td>
                        @{ var prixQuantite = (item.Produit.Prix * @item.Quantite); }
                        @prixQuantite

                    </td>
                    <td>
                        @*<a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |*@
                        <a asp-controller="Produits" asp-action="Details" asp-route-id="@item.ProduitID">Details</a>
                        @*<a asp-action="DeleteArticleDemande" asp-route-id="@item.ID" asp-route-idcomm="@Model.Commande.ID">Delete</a>*@
                        @*<button onclick="deleteProdCom(@item.ProduitID)">Delete</button>*@
                    </td>
                </tr>

                ++i;

            }

        </tbody>
    </table>

</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |*@
    <a asp-action="Index">Retour à la liste</a> 
    <form asp-action="Details" asp-controller="Factures" asp-route-id="@Model.ID">
        <input type="submit" value="Voir la facture" class="btn btn-default" />
    </form>
   
</div>

TFE_GestionDeStockEtVenteEnLigne/Views/Commandes/Index.cshtml
@model IEnumerable<TFE_GestionDeStockEtVenteEnLigne.Models.Commande>

@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Commandes</h2>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
                @*<th>
                    @Html.DisplayNameFor(model => model.RegisterViewModelID)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.DateCommade)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EnCours)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Envoie)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.AdresseFacturation)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Client)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.RegisterViewModelID)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.DateCommade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnCours)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Envoie)
            </td>
            <td>
                @if (item.AdresseFacturation != null)
                {
                    @item.AdresseFacturation.ToString()
                }
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Client.ID)
            </td>*@
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |*@
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> 
                @*<a asp-action="Delete" asp-route-id="@item.ID">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>